domain: "ala-showcase.github.io"
url: "https://ala-showcase.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "ALA Showcase" # the name of your site, e.g. ACME Corp.
description: "Showcase website for the UTS Animal Logic Academy 2023 cohort"

include:
  - _pages

defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename/

navigation:
  - title: Home
    url: /
    icon: bi-house-door
    active: bi-house-door-fill

  - title: Map
    url: /map
    icon: bi-geo-alt
    active: bi-geo-alt-fill

  - title: Artbook
    url: /artbook
    icon: bi-palette
    active: bi-palette-fill

  - title: Graduates
    url: /graduates
    icon: bi-mortarboard
    active: bi-mortarboard-fill
